### ISSUE TITLE
Create workflow for onboarding new classes (and see if this same workflow can apply to NSF centers and labs)

### ISSUE THREAD

**Issue by mitquantumai** [ChatTutor/chattutor#112]
1. Prof should sign up on our website
2. Then we have a discussion with them about their needs
3. They can upload their course materials (which we have to make clear are private and protected, and explicitly state what they should and shouldn't upload)
3. Then we approve the course and make sure the chatbot works on their site as expected (and spider all URLs)
4. Then we deploy for the course
5. Then the profs put the link to the extension in the syllabus
Then when students download the extension, the chatbot only shows up as a drawer option in the top right of the screen on their course website. It sweeps in from the right as a drawer rather than a chatbot pop up.

**Comment by adrianariton** [comment]
Working on this with Andu atm

**Comment by adrianariton** [comment]
working on this on [barosandu_url_spider_db](https://github.com/ChatTutor/chattutor/tree/barosandu_url_spider_db)
