### ISSUE TITLE
Determine how to use the left and right whitespaces for improving UI interactiveness

### ISSUE THREAD

**Issue by mitquantumai** [ChatTutor/chattutor#82]
E.g. if a paper is cited in a response, in one of the whitespaces we can provide a short description of the paper as a pop up and a link to the paper.

Im sure there are plenty of other clever ways to utilize this space for increased interactivity

**Comment by AatmikMallya** [comment]
Low priority (don't do this until the core issues are solved)

**Comment by adrianariton** [comment]
Done in the new PR
