### ISSUE TITLE
Add MathJax latex rendering

### ISSUE THREAD

**Issue by AatmikMallya** [ChatTutor/chattutor#93]

**Comment by adrianariton** [comment]
@dmitrii-briantcev a few days ago the latex rendering worked, but now it does not seem to do so, did you re-parse the chromadb collection?

**Comment by dmitrii-briantcev** [comment]
@adrianariton no, the only thing I did was submit a new pull request. We updated a key for an API so maybe that's the problem. Please get the new branch (beta-main-mathpix-2 I think), and update the .env, I sent the keys in the dev channel in slack. Should work.

**Comment by adrianariton** [comment]
Perfect it works for me too now, can you mark the issue regarding mathjax as solved?
