### ISSUE TITLE
Visual bug on the input box

### ISSUE THREAD

**Issue by AatmikMallya** [ChatTutor/chattutor#94]
This happens when a paper is returned and the user resizes the window. See the bottom write.
![image](https://github.com/AxiomaticAI-Inc/chattutor/assets/50603603/4aea5497-5012-42fd-a68e-c6c72d05f824)

**Comment by adrianariton** [comment]
Could you please resend the image? I can no longer see it

**Comment by adrianariton** [comment]
Is this still an issue?
